//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suitsupply.Alteration.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suitsupply.Alteration.Domain.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date can&apos;t be smaller than request creation date..
        /// </summary>
        internal static string DATE_CAN_NOT_BE_SMALLER {
            get {
                return ResourceManager.GetString("DATE_CAN_NOT_BE_SMALLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer request is not paid or have status diffrent than started..
        /// </summary>
        internal static string FINISHED_OR_WRONG_STATUS {
            get {
                return ResourceManager.GetString("FINISHED_OR_WRONG_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum change of +/- {0} centimeters is allowed..
        /// </summary>
        internal static string MAXIMUM_CHANGE_ONLY_ALLOWED_FORMAT {
            get {
                return ResourceManager.GetString("MAXIMUM_CHANGE_ONLY_ALLOWED_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No alterations provided..
        /// </summary>
        internal static string NO_ALTERATIONS {
            get {
                return ResourceManager.GetString("NO_ALTERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer request is paid or have status diffrent than accepted..
        /// </summary>
        internal static string PAID_OR_WRONG_STATUS {
            get {
                return ResourceManager.GetString("PAID_OR_WRONG_STATUS", resourceCulture);
            }
        }
    }
}
