//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suitsupply.Alteration.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suitsupply.Alteration.Domain.InfoMessages", typeof(InfoMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} extend by {1} centimeters.
        /// </summary>
        internal static string EXTEND_BY_FORMAT {
            get {
                return ResourceManager.GetString("EXTEND_BY_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left sleeve.
        /// </summary>
        internal static string LEFT_SLEEVE {
            get {
                return ResourceManager.GetString("LEFT_SLEEVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left trouser leg.
        /// </summary>
        internal static string LEFT_TROUSER {
            get {
                return ResourceManager.GetString("LEFT_TROUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right sleeve.
        /// </summary>
        internal static string RIGHT_SLEEVE {
            get {
                return ResourceManager.GetString("RIGHT_SLEEVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right trouser leg.
        /// </summary>
        internal static string RIGHT_TROUSER {
            get {
                return ResourceManager.GetString("RIGHT_TROUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} shorten by {1} centimeters.
        /// </summary>
        internal static string SHORTEN_BY_FORMAT {
            get {
                return ResourceManager.GetString("SHORTEN_BY_FORMAT", resourceCulture);
            }
        }
    }
}
